### ISSUE TITLE
Documentation for GymEnvWrapper

### ISSUE THREAD

**Issue by Coolnesss** [astooke/rlpyt#12]
How is GymEnvWrapper supposed to be used? It looked like I should be able to change [this line](https://github.com/astooke/rlpyt/blob/master/examples/example_2.py#L23) to 

```
EnvCls=GymEnvWrapper(gym.make("LunarLanderContinuous-v2"))
```

But I get a rather cryptic error
```python
Traceback (most recent call last):
  File "example_2.py", line 61, in <module>
    cuda_idx=args.cuda_idx,
  File "example_2.py", line 48, in build_and_train
    runner.train()
  File "/Users/chra/tmp/rlpyt/rlpyt/runners/minibatch_rl.py", line 229, in train
    n_itr = self.startup()
  File "/Users/chra/tmp/rlpyt/rlpyt/runners/minibatch_rl.py", line 61, in startup
    world_size=world_size,
  File "/Users/chra/tmp/rlpyt/rlpyt/samplers/serial/sampler.py", line 31, in initialize
    envs = [self.EnvCls(**self.env_kwargs) for _ in range(B)]
  File "/Users/chra/tmp/rlpyt/rlpyt/samplers/serial/sampler.py", line 31, in <listcomp>
    envs = [self.EnvCls(**self.env_kwargs) for _ in range(B)]
TypeError: 'GymEnvWrapper' object is not callable
```

In general, what are the plans for the documentation of this library? The library itself feels very nice but without documentation it's a bit of a struggle to get anything non-trivial going.

**Comment by Coolnesss** [comment]
Okay I figured out that the argument for `EnvCls` must be a function, so I got it to run. Would appreciate comment on the documentation though.

**Comment by arin-kwak** [comment]
Definitely agree! I feel the same. The library seems very good. But it is a little hard to get through source code without document.
