### ISSUE TITLE
Affinity for MultiGPU optimization in a single run

### ISSUE THREAD

**Issue by ankeshanand** [astooke/rlpyt#125]
The affinity stuff was a bit confusing, I wasn't able to figure out how to correctly set it up for using multiple GPUs for optimization. Note that I am doing only a single run. Here's my setup:

```
    affinity = make_affinity(
        n_cpu_core=12,
        n_gpu=4,
        gpu_per_run=3,
        sample_gpu_per_run=1,
        async_sample=True,
        n_socket=1,
        run_slot=0
    )
```

I want to use 4 GPUs for the run (3 for optimization, 1 for sampling) in a single run with asynchronous sampling. 

I get the error 
```
    n_worker = len(affinity["workers_cpus"]) if n_worker is None else n_worker
KeyError: 'workers_cpus'
```

What am I doing wrong with the configuration? 
Sidenote: It would be great to have simpler configuration settings for single run experiments (which I imagine would be a bulk of the use case)

**Comment by ankeshanand** [comment]
I was able to fix this by switching to AsyncRLEval, but I get an unrelated error now: 
```
Process Process-6:
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/v-ankean/.local/lib/python3.6/site-packages/rlpyt/runners/async_rl.py", line 603, in memory_copier
    replay_buffer.append_samples(samples_to_buffer(sample_buffer))
AttributeError: 'NoneType' object has no attribute 'append_samples'
2020-03-15 04:26:53.188146  | dqn_asterix_0 Evaluation reached max num trajectories (5).
Process Process-7:
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/v-ankean/.local/lib/python3.6/site-packages/rlpyt/runners/async_rl.py", line 603, in memory_copier
    replay_buffer.append_samples(samples_to_buffer(sample_buffer))
AttributeError: 'NoneType' object has no attribute 'append_samples'
```

Here's my complete script for posterity:

```python
from rlpyt.agents.dqn.atari.atari_catdqn_agent import AtariCatDqnAgent
from rlpyt.algos.dqn.cat_dqn import CategoricalDQN
from rlpyt.samplers.async_.gpu_sampler import AsyncGpuSampler
from rlpyt.samplers.parallel.gpu.sampler import GpuSampler
from rlpyt.samplers.parallel.gpu.collectors import GpuWaitResetCollector
from rlpyt.envs.atari.atari_env import AtariEnv, AtariTrajInfo
from rlpyt.algos.dqn.dqn import DQN
from rlpyt.agents.dqn.atari.atari_dqn_agent import AtariDqnAgent
from rlpyt.runners.minibatch_rl import MinibatchRlEval
from rlpyt.utils.launching.affinity import encode_affinity, make_affinity, quick_affinity_code, affinity_from_code
from rlpyt.utils.logging.context import logger_context
import wandb

from src.rlpyt_models import MinibatchRlEvalWandb, AsyncRlEvalWandb


def build_and_train(game="ms_pacman", run_ID=0):
    affinity = make_affinity(
        n_cpu_core=12,
        n_gpu=4,
        gpu_per_run=3,
        n_socket=1,
        run_slot=0,
        sample_gpu_per_run=1,
        async_sample=True
    )
    config = dict(
        env=dict(game=game),
        algo=dict(batch_size=128, min_steps_learn=1e4, prioritized_replay=True),
        sampler=dict(batch_T=2, batch_B=32),
    )
    sampler = AsyncGpuSampler(
        EnvCls=AtariEnv,
        TrajInfoCls=AtariTrajInfo,
        env_kwargs=dict(game=game),
        eval_env_kwargs=dict(game=game),
        eval_n_envs=10,
        eval_max_steps=int(10e3),
        eval_max_trajectories=5,
        # batch_T=4,  # Get from config.
        # batch_B=1,
        **config["sampler"]  # More parallel environments for batched forward-pass.
    )
    algo = CategoricalDQN(**config["algo"])  # Run with defaults.
    agent = AtariCatDqnAgent()
    runner = AsyncRlEvalWandb(
        algo=algo,
        agent=agent,
        sampler=sampler,
        n_steps=50e6,
        log_interval_steps=1e3,
        affinity=affinity,
    )
    name = "dqn_" + game
    log_dir = "example"
    with logger_context(log_dir, run_ID, name, config):
        runner.train()


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('--game', help='Atari game', default='pong')
    args = parser.parse_args()
    wandb.init(project='rlpyt')
    build_and_train(
        game=args.game,
        run_ID=args.run_ID
    )
```

Let me know if you want me to create a separate issue for this error.

**Comment by ankeshanand** [comment]
Turns out this is due to a bug in CategoricalDQN with async sampling and has a quick fix as mentioned by @bmazoure in #30. I have created a PR to fix this: https://github.com/astooke/rlpyt/pull/126

**Comment by astooke** [comment]
Seems you were you able to get everything running OK?

Yes sorry for the complication in the affinity, and the most complicated is in the async affinity.  Hopefully the options you need are available?  I'm not 100% sure I tested all the cases there but had enough to get R2D1 running as fast as it can.

**Comment by ankeshanand** [comment]
Yeah, I was able to get it working. Maybe the docs could use info on how to set affinity appropriately, and workarounds around common issues?
