### ISSUE TITLE
Cannot use atari based gym envs

### ISSUE THREAD

**Issue by mwilliammyers** [astooke/rlpyt#127]
I have tried a few different algo/agent/atari gym envs etc combos but nothing seems to work.

I always get a:
```
ValueError: Type names and field names must be valid identifiers: 'ale.lives'
```

<details>
<summary>Full stacktrace</summary>

```
Traceback (most recent call last):
  File "test.py", line 44, in <module>
    build_and_train()
  File "test.py", line 40, in build_and_train
    runner.train()
  File "~/Developer/autorl/.venv/lib/python3.7/site-packages/rlpyt/runners/minibatch_rl.py", line 300, in train
    n_itr = self.startup()
  File "~/Developer/autorl/.venv/lib/python3.7/site-packages/rlpyt/runners/minibatch_rl.py", line 81, in startup
    world_size=world_size,
  File "~/Developer/autorl/.venv/lib/python3.7/site-packages/rlpyt/samplers/parallel/base.py", line 75, in initialize
    env = self.EnvCls(**self.env_kwargs)
  File "~/Developer/autorl/.venv/lib/python3.7/site-packages/rlpyt/envs/gym.py", line 168, in make
    return GymEnvWrapper(gym.make(*args, **kwargs))
  File "~/Developer/autorl/.venv/lib/python3.7/site-packages/rlpyt/envs/gym.py", line 59, in __init__
    build_info_tuples(info)
  File "~/Developer/autorl/.venv/lib/python3.7/site-packages/rlpyt/envs/gym.py", line 100, in build_info_tuples
    globals()[name] = namedtuple(name, list(info.keys()))
  File "/usr/lib/python3.7/collections/__init__.py", line 361, in namedtuple
    raise ValueError('Type names and field names must be valid '
ValueError: Type names and field names must be valid identifiers: 'ale.lives'
```
</details>

<details>
<summary>Minimum example to reproduce</summary>

```python
from rlpyt.agents.dqn.atari.atari_dqn_agent import AtariDqnAgent
from rlpyt.algos.dqn.dqn import DQN
from rlpyt.envs.gym import make as gym_make
from rlpyt.runners.minibatch_rl import MinibatchRlEval
from rlpyt.samplers.parallel.gpu.collectors import GpuWaitResetCollector
from rlpyt.samplers.parallel.gpu.sampler import GpuSampler
from rlpyt.utils.logging.context import logger_context


def build_and_train(env_id="Pong-v4", run_id=0, cuda_idx=0, n_parallel=2):
    sampler = GpuSampler(
        EnvCls=gym_make,
        env_kwargs={"id": env_id},
        CollectorCls=GpuWaitResetCollector,
        eval_env_kwargs={"id": env_id},
        max_decorrelation_steps=0,
        eval_n_envs=10,
        eval_max_steps=10e3,
        eval_max_trajectories=5,
        batch_T=2,
        batch_B=32,
    )
    algo = DQN(batch_size=128)
    agent = AtariDqnAgent()
    runner = MinibatchRlEval(
        algo=algo,
        agent=agent,
        sampler=sampler,
        n_steps=50e6,
        log_interval_steps=1e3,
        affinity=dict(cuda_idx=cuda_idx, workers_cpus=list(range(n_parallel))),
    )

    with logger_context("test", run_id, type(algo).__name__ + env_id):
        runner.train()


if __name__ == "__main__":
    build_and_train()
```
</details>

**Comment by DanielTakeshi** [comment]
@mwilliammyers rlpyt includes built-in handing of Atari environments. From the scripts in the `examples/` directory you just need to specify the game, i.e., "pong" instead of "Pong-v4".

**Comment by mwilliammyers** [comment]
I realize that :)

The docs and other included examples indicate that rlpyt supports gym environments (which it does) but due to the bug I mentioned/fixed in the PR, rlpyt does not support gym environments that wrap Arcade Learning Environments (ALE) like the one you mentioned (`pong`).

We want to use a common interface (gym) and not have to have code to support both gym and ALE envs.

**Comment by kargarisaac** [comment]
It seems that it is not easy to use gym envs with rlpyt, right? I'm trying to use it with CartPole-v0 but I cannot. Do you have any example? Or some example to use rlpyt with custom gym envs.
