### ISSUE TITLE
GymEnvWrapper support for Dict custom envs

### ISSUE THREAD

**Issue by Coolnesss** [astooke/rlpyt#13]
Wondering about the compatibility of `GymEnvWrapper` with Gym `Dict` spaces. Here's a fairly simple example adapted from example 2, with a toy environment that uses a Dict observation space.

```python
from rlpyt.samplers.serial.sampler import SerialSampler
from rlpyt.envs.gym import GymEnvWrapper
from rlpyt.algos.qpg.sac import SAC
from rlpyt.agents.qpg.sac_agent import SacAgent
from rlpyt.runners.minibatch_rl import MinibatchRlEval
from rlpyt.utils.logging.context import logger_context
import gym
from gym.spaces import Box, Dict
import numpy as np


class ExampleEnv(gym.Env):
    def __init__(self):

        self.observation_space = Dict({
            "temperature": Box(-1, 1, shape=(3, 3), dtype=np.float32),
            "energy": Box(low=-1, high=1, shape=(3, ), dtype=np.float32)
        })

        self.action_space = Box(low=-1., high=1., shape=(1, ), dtype=np.float32)

    def step(self, action):
        observation = self.observation_space.sample()
        return observation, 0, False, {}

    def reset(self):
        return self.observation_space.sample()

def f(*args, **kwargs):
    return GymEnvWrapper(ExampleEnv())

def build_and_train():
    sampler = SerialSampler(
        EnvCls=f,
        env_kwargs=dict(id="1"),
        eval_env_kwargs=dict(id="1"),
        batch_T=1,  
        batch_B=1,
        max_decorrelation_steps=0,
        eval_n_envs=10,
        eval_max_steps=int(51e3),
        eval_max_trajectories=50
    )
    algo = SAC()
    agent = SacAgent()
    runner = MinibatchRlEval(
        algo=algo,
        agent=agent,
        sampler=sampler,
        n_steps=1e6,
        log_interval_steps=1e4
    )
    name = "sac_1"
    log_dir = "example_1"
    with logger_context(log_dir, 1, name, {}):
        runner.train()

if __name__ == "__main__":
    build_and_train()

```

 It yields the following error
```python
Traceback (most recent call last):
  File "ppo_rlpyt.py", line 65, in <module>
    build_and_train()
  File "ppo_rlpyt.py", line 58, in build_and_train
    runner.train()
  File "/Users/chra/tmp/rlpyt/rlpyt/runners/minibatch_rl.py", line 229, in train
    n_itr = self.startup()
  File "/Users/chra/tmp/rlpyt/rlpyt/runners/minibatch_rl.py", line 61, in startup
    world_size=world_size,
  File "/Users/chra/tmp/rlpyt/rlpyt/samplers/serial/sampler.py", line 35, in initialize
    global_B=global_B, env_ranks=env_ranks)
  File "/Users/chra/tmp/rlpyt/rlpyt/agents/qpg/sac_agent.py", line 55, in initialize
    global_B=global_B, env_ranks=env_ranks)
  File "/Users/chra/tmp/rlpyt/rlpyt/agents/base.py", line 45, in initialize
    **self.model_kwargs)
  File "/Users/chra/tmp/rlpyt/rlpyt/models/qpg/mlp.py", line 47, in __init__
    input_size=int(np.prod(observation_shape)),
  File "/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2585, in prod
    initial=initial)
  File "/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 83, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
TypeError: can't multiply sequence by non-int of type 'tuple'
```

Am i doing something wrong or is there a bug in the conversion in `GymEnvWrapper`?

**Comment by Coolnesss** [comment]
Hey, got it. I guess a model change is required either way, since I need to decide how the observations are fed into the model (flattened out, as channels to a convnet, etc).

**Comment by sufengniu** [comment]
@Coolnesss @astooke I tried to run the above sample code, but I got `AttributeError: can't set attribute` do you have any clues how to resolve it?
