### ISSUE TITLE
How can I run atari_dqn_async_gpu.py with n_gpu=1?

### ISSUE THREAD

**Issue by wkentaro** [astooke/rlpyt#162]
Hi, I'm having below error when I run examples/atari_dqn_async_gpu.py with a small modification. Does anyone have any idea what's the issue around this?

```bash
% python atari_dqn_async_gpu.py 
Traceback (most recent call last):
  File "atari_dqn_async_gpu.py", line 73, in <module>
    run_ID=args.run_ID,
  File "atari_dqn_async_gpu.py", line 25, in build_and_train
    optim_sample_share_gpu=False,
  File "/home/wkentaro/pickpp/src/rlpyt/rlpyt/utils/launching/affinity.py", line 162, in make_affinity
    return affinity_from_code(encode_affinity(run_slot=run_slot, **kwargs))
  File "/home/wkentaro/pickpp/src/rlpyt/rlpyt/utils/launching/affinity.py", line 153, in affinity_from_code
    return build_async_affinity(run_slot, **aff_params)
  File "/home/wkentaro/pickpp/src/rlpyt/rlpyt/utils/launching/affinity.py", line 283, in build_async_affinity
    assert run_slot < n_run_slots
AssertionError
```

```diff
@ examples/atari_dqn_async_gpu.py:20 @ def build_and_train(game="pong", run_ID=0):
    # Change these inputs to match local machine and desired parallelism.
    affinity = make_affinity(
        run_slot=0,
        n_cpu_core=8,  # Use 16 cores across all experiments.
        n_gpu=2,  # Use 8 gpus across all experiments.
        n_cpu_core=6,  # Use 16 cores across all experiments.
        n_gpu=1,  # Use 8 gpus across all experiments.
        gpu_per_run=1,
        sample_gpu_per_run=1,
        async_sample=True,
```

**Comment by astooke** [comment]
Hi!  Can you clarify what inputs you are passing to `make_affinity()`?  It looks like you pass the same kwarg multiple times.

And yes the affinities are kind of a complicated part of all this, not sure that the async affinities are fully flexible to different compute resources.

**Comment by wkentaro** [comment]
Oh, sorry, my git diff didn't show +-.
```diff
@ examples/atari_dqn_async_gpu.py:20 @ def build_and_train(game="pong", run_ID=0):
     # Change these inputs to match local machine and desired parallelism.
     affinity = make_affinity(
         run_slot=0,
-        n_cpu_core=8,  # Use 16 cores across all experiments.
-        n_gpu=2,  # Use 8 gpus across all experiments.
+        n_cpu_core=6,  # Use 16 cores across all experiments.
+        n_gpu=1,  # Use 8 gpus across all experiments.
         gpu_per_run=1,
         sample_gpu_per_run=1,
         async_sample=True,
```

**Comment by astooke** [comment]
OK I think you might be able to fix this by using the kwarg: `optim_sample_share_gpu=True`.  Otherwise it will try to assign different GPUs to sampling vs training, and ofc can't do that with just one ;)

Does that work?

**Comment by wkentaro** [comment]
It worked. Thanks!
