### ISSUE TITLE
KeyError: 'action'

### ISSUE THREAD

**Issue by csingh27** [astooke/rlpyt#205]
As I run the launch script, I get this error and I am unable to find a solution to this for long. Does anyone know about this ? 

Here is the full error : 
  File "/home/chandandeep/.mujoco/rlpyt/rlpyt/experiments/scripts/dm_control/qpg/sac/train/dm_control_sac.py", line 64, in <module>
    build_and_train(*sys.argv[1:])
  File "/home/chandandeep/.mujoco/rlpyt/rlpyt/experiments/scripts/dm_control/qpg/sac/train/dm_control_sac.py", line 60, in build_and_train
    runner.train()
  File "/home/chandandeep/.mujoco/rlpyt/rlpyt/runners/minibatch_rl.py", line 230, in train
    n_itr = self.startup() # 12500
  File "/home/chandandeep/.mujoco/rlpyt/rlpyt/runners/minibatch_rl.py", line 62, in startup
    world_size=world_size,
  File "/home/chandandeep/.mujoco/rlpyt/rlpyt/samplers/parallel/base.py", line 60, in initialize
    examples = self._build_buffers(self.EnvCls, self.env_kwargs, bootstrap_value)
  File "/home/chandandeep/.mujoco/rlpyt/rlpyt/samplers/parallel/base.py", line 162, in _build_buffers
    agent_shared=True, env_shared=True, subprocess=True)
  File "/home/chandandeep/.mujoco/rlpyt/rlpyt/samplers/buffer.py", line 43, in build_samples_buffer
    all_action = buffer_from_example(examples["action"], (T + 1, B), agent_shared)
  File "<string>", line 2, in __getitem__
  File "/home/chandandeep/anaconda3/envs/rlpyt/lib/python3.7/multiprocessing/managers.py", line 834, in _callmethod
    raise convert_to_error(kind, result)
KeyError: 'action'

**ALSO**, I get the following error and I suspect the above error is because of this since it does not get values for examples :
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 131 requests (131 known processed) with 0 events remaining.

**EDIT** : 
When I change display to "export DISPLAY=localhost:0.0", then the error changes
/home/chandandeep/anaconda3/envs/rlpyt/lib/python3.7/site-packages/glfw/__init__.py:834: GLFWError: (65537) b'The GLFW library is not initialized'
  warnings.warn(message, GLFWError)
python: /builds/florianrhiem/pyGLFW/glfw-3.3.2/src/posix_thread.c:64: _glfwPlatformGetTls: Assertion `tls->posix.allocated == 1' failed.
Traceback (most recent call last):
  File "/home/chandandeep/.mujoco/rlpyt/rlpyt/experiments/scripts/dm_control/qpg/sac/train/dm_control_sac.py", line 64, in <module>
    build_and_train(*sys.argv[1:])
  File "/home/chandandeep/.mujoco/rlpyt/rlpyt/experiments/scripts/dm_control/qpg/sac/train/dm_control_sac.py", line 60, in build_and_train
    runner.train()
  File "/home/chandandeep/.mujoco/rlpyt/rlpyt/runners/minibatch_rl.py", line 230, in train
    n_itr = self.startup() # 12500
  File "/home/chandandeep/.mujoco/rlpyt/rlpyt/runners/minibatch_rl.py", line 62, in startup
    world_size=world_size,
  File "/home/chandandeep/.mujoco/rlpyt/rlpyt/samplers/parallel/base.py", line 51, in initialize
    env_spaces = self._get_env_spaces(self.EnvCls, self.env_kwargs)
  File "/home/chandandeep/.mujoco/rlpyt/rlpyt/samplers/parallel/base.py", line 134, in _get_env_spaces
    return examples['spaces']
  File "<string>", line 2, in __getitem__
  File "/home/chandandeep/anaconda3/envs/rlpyt/lib/python3.7/multiprocessing/managers.py", line 834, in _callmethod
    raise convert_to_error(kind, result)
KeyError: 'spaces'

**Comment by csingh27** [comment]
@astooke

**Comment by tsuchishinka** [comment]
I have the same error with you. Have you solved it? it?Please

**Comment by tsuchishinka** [comment]
> @astooke
I have the same error with you. Have you solved it? it?Please

**Comment by csingh27** [comment]
I quit using this framework and switched to Stable Baselines. I wish there was better support with this.
