### ISSUE TITLE
'R2D1' object has no attribute 'compute_priorities'?

### ISSUE THREAD

**Issue by yanzhenqiang** [astooke/rlpyt#22]
Traceback (most recent call last):
  File "rlpyt/experiments/scripts/atari/dqn/train/atari_r2d1_gpu.py", line 47, in <module>
    build_and_train(*sys.argv[1:])
  File "rlpyt/experiments/scripts/atari/dqn/train/atari_r2d1_gpu.py", line 43, in build_and_train
    runner.train()
  File "/home/yanzhenqiang/oops/rlpyt/rlpyt/runners/minibatch_rl.py", line 238, in train
    opt_info = self.algo.optimize_agent(itr, samples)
  File "/home/yanzhenqiang/oops/rlpyt/rlpyt/algos/dqn/r2d1.py", line 130, in optimize_agent
    priorities = self.compute_priorities(samples)
AttributeError: 'R2D1' object has no attribute 'compute_priorities'

**Comment by astooke** [comment]
thanks, just fixed!  I must've only run the latest version in asynchronous sampling mode, where the optimizer process wouldn't be the one to add samples to the replay buffer.
