### ISSUE TITLE
ZeroDivisionError in Sequence N-Step ReplayBuffer when rnn_state_interval == 0 (No rnn state)

### ISSUE THREAD

**Issue by wangwwno1** [astooke/rlpyt#24]
According to func `extract_batch`, when `self.rnn_state_interval` is 0, the buffer shall return `init_rnn_state` with `None`.
However, a `ZeroDivisionError` raised during initialization of buffer.
Possible Cause: **Missing indent** in the last line of `SequenceNStepReturnBuffer.__init__`.

File Path: \rlpyt\rlpyt\replays\sequence\n_step.py
```
class SequenceNStepReturnBuffer(BaseNStepReturnBuffer):

    def __init__(self, example, size, B, rnn_state_interval, batch_T=None, **kwargs):
        # ...Do Something
        if rnn_state_interval > 1:
            assert self.T % rnn_state_interval == 0
        self.rnn_T = self.T // rnn_state_interval  # -> Missing indent?

    def extract_batch(self, T_idxs, B_idxs, T):
        """Return full sequence of each field which encompasses all subsequences
        to be used, so algorithm can make sub-sequences by slicing on device,
        for reduced memory usage."""
        s, rsi = self.samples, self.rnn_state_interval
        if rsi > 1:
            assert np.all(np.asarray(T_idxs) % rsi == 0)
            init_rnn_state = self.samples_prev_rnn_state[T_idxs // rsi, B_idxs]
        elif rsi == 1:
            init_rnn_state = self.samples.prev_rnn_state[T_idxs, B_idxs]
        else:  # rsi == 0
            init_rnn_state = None
        # Do Other things...
```

Here is the Traceback:
```
Traceback (most recent call last):
  File "D:\Code_Studios\PyCharm 2019.1.3\helpers\pydev\pydevd.py", line 1758, in <module>
    main()
  File "D:\Code_Studios\PyCharm 2019.1.3\helpers\pydev\pydevd.py", line 1752, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Code_Studios\PyCharm 2019.1.3\helpers\pydev\pydevd.py", line 1147, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Code_Studios\PyCharm 2019.1.3\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Data_Compressed/PyCharm-Workspace/RobertWang's Wheel/models/rlpyt_API/Test.py", line 62, in <module>
    cuda_idx=args.cuda_idx,
  File "D:/Data_Compressed/PyCharm-Workspace/RobertWang's Wheel/models/rlpyt_API/Test.py", line 49, in build_and_train
    runner.train()
  File "d:\data\github\rlpyt\rlpyt\runners\minibatch_rl.py", line 229, in train
    n_itr = self.startup()
  File "d:\data\github\rlpyt\rlpyt\runners\minibatch_rl.py", line 75, in startup
    rank=rank,
  File "D:\Data_Compressed\PyCharm-Workspace\RobertWang's Wheel\models\rlpyt_API\algo\GraphConvDDPG.py", line 81, in initialize
    self.initialize_replay_buffer(examples, batch_spec)
  File "D:\Data_Compressed\PyCharm-Workspace\RobertWang's Wheel\models\rlpyt_API\algo\GraphConvDDPG.py", line 131, in initialize_replay_buffer
    self.replay_buffer = ReplayCls(**replay_kwargs)
  File "d:\data\github\rlpyt\rlpyt\replays\sequence\n_step.py", line 39, in __init__
    self.rnn_T = self.T // rnn_state_interval
ZeroDivisionError: integer division or modulo by zero
```

**Comment by astooke** [comment]
Thanks, that seems right, like `self.rnn_T` is only used if `rnn_state_interval>1`.  Just added the indentation!
