### ISSUE TITLE
atari_dqn_async_cpu.py not working

### ISSUE THREAD

**Issue by lidongke** [astooke/rlpyt#33]
HI~
When I run atari_dqn_async_cpu.py , i get this error:
```
Traceback (most recent call last):
  File "./atari_dqn_async_cpu.py", line 70, in <module>
    run_ID=args.run_ID,
  File "./atari_dqn_async_cpu.py", line 23, in build_and_train
    async_sample=True,
  File "/home/me/rlpyt/rlpyt/utils/launching/affinity.py", line 131, in make_affinity
    return affinity_from_code(encode_affinity(run_slot=run_slot, **kwargs))
  File "/home/me/rlpyt/rlpyt/utils/launching/affinity.py", line 122, in affinity_from_code
    return build_async_affinity(run_slot, **aff_params)
  File "/home/me/rlpyt/rlpyt/utils/launching/affinity.py", line 274, in build_async_affinity
    assert gpr % skt_per_run == 0, "Maybe try n_socket=1."
AssertionError: Maybe try n_socket=1.``
```
If i set n_socket=1 ,i get another error:
```
logger_context received log_dir outside of /home/me/rlpyt/data: prepending by /home/me/rlpyt/data/local/<yyyymmdd>/
using seed 1298
2019-10-09 12:06:27.375515  | async_dqn_pong_0 Running 50000 sampler iterations.
2019-10-09 12:06:27.378948  | async_dqn_pong_0 Frame-based buffer using 4-frame sequences.
2019-10-09 12:06:27.858403  | async_dqn_pong_0 Agent setting min/max epsilon itrs: 250, 25000
2019-10-09 12:06:27.868091  | async_dqn_pong_0 Optimizer master CPU affinity: [0, 10].
2019-10-09 12:06:27.868410  | async_dqn_pong_0 Optimizer master Torch threads: 1.
2019-10-09 12:06:27.916840  | async_dqn_pong_0 Initialized async CPU agent model.
2019-10-09 12:06:27.917136  | async_dqn_pong_0 Total parallel evaluation envs: 2.
using seed 1298
using seed 1299
2019-10-09 12:06:28.488460  | async_dqn_pong_0 Sampler rank 0 initialized, CPU affinity [1, 11], Torch threads 1, Seed 1298
2019-10-09 12:06:28.492437  | async_dqn_pong_0 Sampler rank 1 initialized, CPU affinity [2, 12], Torch threads 1, Seed 1299
2019-10-09 12:06:29.513263  | async_dqn_pong_0 Sampler decorrelating envs, max steps: 100
Process Process-5:2:
Traceback (most recent call last):
  File "/home/me/anaconda3/envs/rlpyt/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/me/anaconda3/envs/rlpyt/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/me/rlpyt/rlpyt/samplers/parallel/worker.py", line 51, in sampling_process
    agent_inputs, traj_infos = collector.start_envs(c.max_decorrelation_steps)
  File "/home/me/rlpyt/rlpyt/samplers/collectors.py", line 104, in start_envs
    self.step_buffer_np.observation[:] = observation
AttributeError: 'NoneType' object has no attribute 'observation'
Process Process-5:1:
Traceback (most recent call last):
  File "/home/me/anaconda3/envs/rlpyt/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/me/anaconda3/envs/rlpyt/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/me/rlpyt/rlpyt/samplers/parallel/worker.py", line 51, in sampling_process
    agent_inputs, traj_infos = collector.start_envs(c.max_decorrelation_steps)
  File "/home/me/rlpyt/rlpyt/samplers/collectors.py", line 104, in start_envs
    self.step_buffer_np.observation[:] = observation
AttributeError: 'NoneType' object has no attribute 'observation'
2019-10-09 12:06:30.455029  | async_dqn_pong_0 Initialized agent model on device: cuda:0
```
@astooke

**Comment by astooke** [comment]
Hi!  Yes the first error is kind of a known problem and using `n_socket=1` is a good way around it.

But the second error shouldn't happen.  It should be fixed in:  02963ce9b733ae9d7e24b7756daa9ec38d51098f

Are you up to date with this line of code above that?
https://github.com/astooke/rlpyt/blob/8331b7f919bcecd3dfe9ece85d2fb479d471ff6f/rlpyt/samplers/collectors.py#L104

(probably not because that's the new Line 104)

Pull and let us know?

**Comment by lidongke** [comment]
Thanks! I fixed that after pull your commit. I have another question, if the rlpyt can parallel training and sampling , i mean that like OpenAI's baselines, training will block samling , they are serial.

**Comment by astooke** [comment]
Glad that fixed it!

I think the answer to your question is that, in the async runner, sampling and training happen in parallel (in separate processes), but in the other runners, sampling and training happen in serial in the same process.  This is described in a little more detail in the white paper: https://arxiv.org/abs/1909.01500

**Comment by lidongke** [comment]
Thanks ! You can close this issue.
