### ISSUE TITLE
Making the multi-cpu single-gpu setup work on cluster

### ISSUE THREAD

**Issue by bmazoure** [astooke/rlpyt#68]
I'm trying to run the default affinity set up on a cluster node with 40 CPUs (all same architecture) and 2 GPUs (V100), but run into the following error:
```
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2017/Core/python/3.6.3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bmazoure/rlpyt/rlpyt/samplers/parallel/worker.py", line 37, in sampling_process
    initialize_worker(w.rank, w.seed, w.cpus, c.torch_threads)
  File "/home/bmazoure/rlpyt/rlpyt/samplers/parallel/worker.py", line 17, in initialize_worker
    p.cpu_affinity(cpu)
  File "/home/bmazoure/pytorch_gpu/lib/python3.6/site-packages/psutil/__init__.py", line 937, in cpu_affinity
    self._proc.cpu_affinity_set(list(set(cpus)))
  File "/home/bmazoure/pytorch_gpu/lib/python3.6/site-packages/psutil/_pslinux.py", line 1507, in wrapper
    return fun(self, *args, **kwargs)
  File "/home/bmazoure/pytorch_gpu/lib/python3.6/site-packages/psutil/_pslinux.py", line 1944, in cpu_affinity_set
    cext.proc_cpu_affinity_set(self.pid, cpus)
OSError: [Errno 22] Invalid argument
```

The affinity is as follows:
```
affinity = make_affinity(
                    n_cpu_core=8,
                    n_gpu=1,
                    hyperthread_offset=8,
                    n_socket=2,
                )
```

What could be causing such an issue?

**Comment by bmazoure** [comment]
I actually managed to fix this (after some debugging):

```
affinity = make_affinity(
                    n_cpu_core=4,
                    n_gpu=1,
                    hyperthread_offset=0
                )
        # This is here to allow scheduling of non-sequential CPU IDs
        import psutil
        psutil.Process().cpu_affinity([])
        cpus = tuple(psutil.Process().cpu_affinity())
        affinity['all_cpus'] = affinity['master_cpus'] = cpus
        affinity['workers_cpus'] = tuple([tuple([x]) for x in cpus+cpus])
```

On some cluster setups, requesting N CPUs out of M leads to the CPU IDs being non-sequential. E.g. you can get four CPUs as `[0,5,20,72]`, which is why we need to re-assign the CPU IDs from the list of available ones. @astooke does that make sense?

**Comment by astooke** [comment]
Yeah all the built-in functions for making the affinity assume you have sequential CPU IDs (was always just for running locally on a machine).  When running on a cluster, I've also had to make custom affinity builders.  

Yes, if your cluster manager ends up exposing the actual CPU IDs you are assigned via psutil, you could just make your own affinity like:

```python
cpus = psutil.Process.cpu_affinity()   # should return a list or a tuple  
affinity=dict(
    cuda_idx=gpu,  # whichever one you have
    master_cpus=cpus,
    workers_cpus=list([x] for x in cpus),  # If just one cpu per worker
    set_affinity=True,  # can set to False if you want to turn off rlpyt assigning the psutil cpu_affinity
)   
```

I've run on some clusters where you get assigned some number of CPUs but if you call psutil, it says you have access to all of them, so I gave up trying to pin the individual processes and just made `set_affinity=False`.  Maybe that can still run fast.
