### ISSUE TITLE
PPO alternating sampler example_3 error

### ISSUE THREAD

**Issue by AlexanderKoch-Koch** [astooke/rlpyt#86]
when I execute the example_3 script with the alternating sampler I get an error:
python3 example_3.py --sample_mode=alternating

Using Alternating GPU parallel sampler, CPU for sampling and optimizing.
logger_context received log_dir outside of /home/alex/rlpyt/data: prepending by /home/alex/rlpyt/data/local/<yyyymmdd>/
2019-12-16 19:38:30.218304  | a2c_pong_0 Runner  master CPU affinity: [0, 1, 2, 3, 4, 5, 6, 7].
2019-12-16 19:38:30.218379  | a2c_pong_0 Runner  master Torch threads: 4.
using seed 2342
using seed 2344
using seed 2343
using seed 2346
using seed 2345
2019-12-16 19:38:30.965334  | a2c_pong_0 Sampler rank 0 initialized, CPU affinity [0], Torch threads 1, Seed 2343
2019-12-16 19:38:30.965335  | a2c_pong_0 Sampler rank 1 initialized, CPU affinity [1], Torch threads 1, Seed 2344
2019-12-16 19:38:30.978913  | a2c_pong_0 Sampler rank 3 initialized, CPU affinity [1], Torch threads 1, Seed 2346
2019-12-16 19:38:30.978913  | a2c_pong_0 Sampler rank 2 initialized, CPU affinity [0], Torch threads 1, Seed 2345
2019-12-16 19:38:32.262018  | a2c_pong_0 Sampler decorrelating envs, max steps: 400
2019-12-16 19:38:33.292149  | a2c_pong_0 Running 625000 iterations of minibatch RL.
2019-12-16 19:38:33.292695  | a2c_pong_0 Optimizing over 1250 iterations.
Traceback (most recent call last):
  File "example_3.py", line 80, in <module>
    n_parallel=args.n_parallel,
  File "example_3.py", line 62, in build_and_train
    runner.train()
  File "/home/alex/rlpyt/rlpyt/runners/minibatch_rl.py", line 196, in train
    samples, traj_infos = self.sampler.obtain_samples(itr)
  File "/home/alex/rlpyt/rlpyt/samplers/parallel/gpu/sampler.py", line 31, in obtain_samples
    self.serve_actions(itr)  # Worker step environments here.
  File "/home/alex/rlpyt/rlpyt/samplers/parallel/gpu/action_server.py", line 127, in serve_actions
    self.bootstrap_value_pair[alt][:] = self.agent.value(*agent_inputs_pair[alt])
ValueError: could not broadcast input array from shape (8) into shape (1,16)

**Comment by astooke** [comment]
Hmm, good catch, I'll run this again and see...

**Comment by astooke** [comment]
Good catch!  Fixed (finally!) in commit c10784462abff220233d965b91fcfd895c8ebf9a

Had to account for the leading T=1 dim in the bootstrap_value buffer.
